#!/bin/bash
if [[ ! $1 ]]; then
	echo "creates a copy of the file or dirrectory in the same dirrectory with the same name but with added .bak "
	echo "    usage: bak FILENAME [-no]"
	echo "    -no: no overrides, do not overrides existing copy"
	exit 1
fi

if [[ $1 ]] && ([[ -f $1 ]] || [[ -d $1 ]]); then
	if [[ $2 ]] && [[ $2 == "-no" ]] && ( [[ -f $1 ]] || [[ -d $1 ]] ); then
		echo "$1.bak already exists, exiting"
		exit 1	
	fi
	echo "backuping file $1"

	FILENAME=$1
	suffix="/"
	FILENAME="a/"	
	FILENAME=${FILENAME%"$suffix"}

	cp -r $FILENAME $FILENAME.bak
else
	echo "file $FILENAME not found"
fi

