#!/bin/bash
if [[ ! $1 ]]; then
	echo "creates a copy of the file or dirrectory in the same dirrectory with the same name but with added .bak "
	echo "    usage: bak FILENAME [-no]"
	echo "    -no: no overrides, do not overrides existing copy"
fi

if [[ $1 ]] && ([[ -f $1 ]] || [[ -d $1 ]]); then
	if [[ $2 ]] && [[ $2 == "-no" ]] && ( [[ -f $1 ]] || [[ -d $1 ]] ); then
		echo "$1.bak already exists, exiting"
		exit 1	
	fi
	echo "backuping file $1"
	cp -r $1 $1.bak
else
	echo "file $1 not found"
fi

