#!/bin/bash

show_help(){
	echo "creates a copy of the file or dirrectory in the same dirrectory with the same name but with added .bak "
	echo "    usage: bak filename [options]"
	echo "    options:"
	echo "           -h:                      show help and exit"
	echo "    	     -n    --no_override:     do not override existing copy"
	echo "    	     -d -r --delete: 	     removes original"
	exit 1
}

if [[ ! $1 ]]; then
	show_help
fi

OPTS=`getopt -o nrdh --long no_override,delete,remove,help -n 'parse-options' -- "$@"`

for i in $OPTS; do
	case "$i" in
		-h | --help							) show_help; ;;
		-n | --no_override 					) no_override=true;  ;;
		-d | --delete | -r | --remove		) delete=true;  ;;
		-- ) break ;;
		* ) break ;;
	esac
done


SAVEIFS=$IFS
IFS=$(echo -en "\n\b")
target_supplied=0
for i in $@; do
	if [[ ${i:0:1} != "-" ]]; then
		if [[ $target_supplied == 0 ]]; then

			if [[ -f "$i" ]] || [[ -d "$i" ]]; then
				original="$i"
				copy="$i.bak"
				target_supplied=1
			else 
				echo -e "File \033[33m$i\033[0m not found"
				IFS=$SAVEIFS
				exit 1
			fi
		else
			echo "Only one target could be copied"
			IFS=$SAVEIFS
			exit 1
		fi
	fi
done


if [[ $original = "" ]]; then
	show_help	
fi

if [[ $no_override == true ]] && ( [[ -f $copy ]] || [[ -d $copy ]] ); then
	echo -e "\033[33m$copy\033[0m already exists, doing nothing"
	IFS=$SAVEIFS
	exit 2
fi

echo -en "Backuping file \033[33m$original\033[0m to \033[33m$copy\033[0m"
cp -Trfa --strip-trailing-slashes $original $copy
if [[ $delete == true ]]; then
	if [[ $? == 0 ]]; then
		echo -e " and removing the original (\033[33m$original\033[0m)"
		rm -rf $original
	else
		echo " (copy failed with error $?, not removing anything)"
	fi
else 
	echo
fi

IFS=$SAVEIFS

exit $?