#!/bin/bash
if [[ ! $1 ]]; then
	echo restoring previously backed up copy of the file 
	echo     usage: unbak FILENAME [-r]
	echo            -r: deletes the copy
	exit 1
fi

backupname=$1.bak
if [[ $1 ]] && ([[ -f $backupname ]] || [[ -d $backupname ]]); then
	cp -r $backupname $1
	echo "restoring file $backupname"
	if [[ $2 == "-r" ]]; then
		rm -rf $backupname
		echo "and removing backup"
	fi
else
	echo "backuped file $1 not found"
fi

