#!/bin/bash
if [[ ! $1 ]]; then
	echo restoring previously backed up copy of the file 
	echo     usage: unbak FILENAME [-r]
	echo            -r: deletes the copy
	exit 1
fi

backupname=$1
suffix="/"
backupname="a/"	
backupname=${backupname%"$suffix"}
backupname=$backupname.bak

if [[ $1 ]] && ([[ -f $backupname ]] || [[ -d $backupname ]]); then
	echo "restoring file $backupname"
	cp -r $backupname $1
	if [[ $2 == "-r" ]]; then
		echo "and removing backup"
		rm -rf $backupname
	fi
else
	echo "backuped file $1 not found"
fi

